version: '3.5'

services:
  oa-vue-ph_build:
    build:
      context: .
      dockerfile: Dockerfile.stage
    container_name: 'oa-vue-ph_build'
    volumes:
      - oa-vue-ph_dist:/code/dist

  oa-vue-ph_web:
    image: nginx
    ports:
      - 8001:80
    container_name: 'oa-vue-ph_web'
    restart: unless-stopped
    volumes:
      - oa-vue-ph_dist:/usr/share/nginx/html:ro
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  oa-vue-ph_dist: